version: '2'

volumes:
  documentos_1g: {}
  documentos_2g: {}
  download: {}
  eproc_tmp: {}
  mysql_data: {}
  upload: {}

services:
  memcached:
    image: registry.stm.jus.br/eproc-memcached-1:latest
  mysql:
    image: registry.stm.jus.br/eproc-mysql-8:latest
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/mysql/docker-entrypoint-initdb.d/00-users.sql:/docker-entrypoint-initdb.d/00-users.sql:ro
      - ./config/mysql/docker-entrypoint-initdb.d/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./config/mysql/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./config/mysql/etc/mysql/conf.d/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf:ro
      - mysql_data:/var/lib/mysql:rw
  nginx:
    image: registry.stm.jus.br/eproc-nginx-1:latest
    ports:
      - "20080:80"
    depends_on:
      - php
    links:
      - 'php:php'
    volumes:
      - ./config/nginx/etc/nginx/conf.d/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf:ro
      - ./config/nginx/etc/nginx/conf.d/www-eproc2-local-1g.desenv.stm.conf:/etc/nginx/conf.d/www-eproc2-local-1g.desenv.stm.conf:ro
      - ./config/nginx/etc/nginx/conf.d/www-eproc2-local-2g.desenv.stm.conf:/etc/nginx/conf.d/www-eproc2-local-2g.desenv.stm.conf:ro
      - E:/Workspaces/projects-stm/eproc_trf4/eproc2:/var/www/eproc2:ro
  php:
    image: registry.stm.jus.br/eproc-php-72:latest
    depends_on:
      - memcached
      - mysql
      - solr
    links:
      - 'mysql:mysql'
      - 'solr:solr'
    volumes:
      - ./config/php/usr/local/etc/php/conf.d/eproc.ini:/usr/local/etc/php/conf.d/eproc.ini:ro
      - ./config/php/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./config/php/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - download:/download:rw
      - documentos_1g:/var/eproc/documentos-1g:rw
      - documentos_2g:/var/eproc/documentos-2g:rw
      - upload:/var/upload:rw
      - eproc_tmp:/var/www/eproc_tmp:rw
      - E:/Workspaces/projects-stm/eproc_trf4/eproc2:/var/www/eproc2:ro
  solr:
    image: registry.stm.jus.br/eproc-solr-8:latest
    ports:
      - 28983:8983
